"""왜 안돼

Revision ID: 72c1805e51b8
Revises: 82cf7315a52b
Create Date: 2021-08-24 21:38:11.741877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c1805e51b8'
down_revision = '82cf7315a52b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('awardhistory',
    sa.Column('userid', sa.String(length=50), nullable=False),
    sa.Column('awardshistory', sa.String(length=50), nullable=True),
    sa.Column('detailhistory', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('certification',
    sa.Column('userid', sa.String(length=50), nullable=False),
    sa.Column('certifiname', sa.String(length=50), nullable=True),
    sa.Column('certifiprov', sa.String(length=50), nullable=True),
    sa.Column('certifidate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('education',
    sa.Column('userid', sa.String(length=50), nullable=False),
    sa.Column('schoolname', sa.String(length=50), nullable=True),
    sa.Column('major', sa.String(length=50), nullable=True),
    sa.Column('degree', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('projecthistory',
    sa.Column('userid', sa.String(length=50), nullable=False),
    sa.Column('projectname', sa.String(length=50), nullable=True),
    sa.Column('projectdetail', sa.String(length=50), nullable=True),
    sa.Column('projectdate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('user_info',
    sa.Column('userid', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=True),
    sa.Column('oneline', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    op.create_table('users',
    sa.Column('userid', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=500), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('userid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_info')
    op.drop_table('projecthistory')
    op.drop_table('education')
    op.drop_table('certification')
    op.drop_table('awardhistory')
    # ### end Alembic commands ###
